### ISSUE TITLE
Bug: Errors with symlinks in staging area and markdownlint

### ISSUE THREAD

**Issue by brynary** [qltysh/qlty#1231]
### What happened?

We have symlinks committed in our repo. We are seeing errors when a full build runs, initially during the staging phase and then markdownlint crashes.

### What did you expect to happen?

Successful completion of build

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qlty 0.452.0 (3124098)

### Relevant log output

```shell
2024-11-27T00:11:31Z ERROR [ThreadId(8)]::qlty_check::executor::staging_area (20.4 MB): Error reading metadata for: "/home/runner/work/cloud/cli/Cargo.toml"
2024-11-27T00:11:31Z ERROR [ThreadId(7)]::qlty_check::executor::staging_area (20.4 MB): Error reading metadata for: "/home/runner/work/cloud/cli/LICENSE.md"
2024-11-27T00:11:31Z ERROR [ThreadId(7)]::qlty_check::executor::staging_area (20.4 MB): Error reading metadata for: "/home/runner/work/cloud/cli/README.md"
2024-11-27T00:11:31Z ERROR [ThreadId(5)]::qlty_check::executor::staging_area (20.4 MB): Error reading metadata for: "/home/runner/work/cloud/cli/SECURITY.md"
2024-11-27T00:11:31Z ERROR [ThreadId(7)]::qlty_check::executor (20.6 MB): Failed to load config file from repository: Failed to copy config file /home/runner/work/cloud/cli/Cargo.toml to /home/runner/tmp/qlty/qkV1sVRl-rw/cli/Cargo.toml
Caused by:
    No such file or directory (os error 2)

...

2024-11-27T00:12:12Z ERROR [ThreadId(78)]::qlty_check::executor::invocation_result (29.8 MB): 59eIc6: markdownlint/lint STDERR: Error: ENOENT: no such file or directory, open 'cli/SECURITY.md'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at lintFile (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint/lib/markdownlint.js:887:33)
    at lintWorker (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint/lib/markdownlint.js:977:7)
    at lintInput (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint/lib/markdownlint.js:1018:7)
    at Function.markdownlintSync [as sync] (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint/lib/markdownlint.js:1067:3)
    at lintAndPrint (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint-cli/markdownlint.js:327:35)
    at Object.<anonymous> (/home/runner/.qlty/cache/tools/markdownlint/0.42.0-440d039728e1/node_modules/markdownlint-cli/markdownlint.js:333:5)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'cli/SECURITY.md'
}
```

**Comment by marschattha** [comment]
This related to https://github.com/qltysh/cloud/pull/5018

Basically right now we don't pull the submodule, but the symlinks are there pointing to the files causing this. 

But as I said in that PR, it makes more sense to have the symlinked files ignored since they are scanned as part of this repo.

**Comment by brynary** [comment]
Closing this as submodules are currently unsupported
